### ISSUE TITLE
正在使用，但是太不稳定，经常调整设置后打不开网页

### ISSUE THREAD

**Issue by Myzhivago** [cary-sas/v2ray_bin#1]
好像是添加的SmartDNS的问题，不用SmartDNS似乎好些，还在测试中

**Comment by Myzhivago** [comment]
原来FancySS插件可稳定很多，我用的是Ac68U 380 7.9.1 固件

**Comment by cary-sas** [comment]
> 好像是添加的SmartDNS的问题，不用SmartDNS似乎好些，还在测试中

尽量不要用smartDNS，除非你很了解那个配置

**Comment by Myzhivago** [comment]
非常好的一个插件，希望你不断完善他，我现在退到没有加入Trojan-go前面的版本，也没用SmartDNS, 目前还好

非常感谢你专门给我回信

**Comment by he583899772** [comment]
RT-AX86U 离线安装提示 ，没有找到插件的web页面
固件版本 386.2_6，是不支持吗，找了好多，xray的插件想替换v2ray

【2021年07月24日 14:50:35】: ========================== step 1 ===============================
【2021年07月24日 14:50:35】: 开启插件离线安装！
【2021年07月24日 14:50:36】: 检测到你上传的离线安装包：shadowsocks.tar.gz，安装包大小: 25.5M
【2021年07月24日 14:50:36】: 安装包md5sum校验值：f5423526ff735089a2c270fd970a7e34
【2021年07月24日 14:50:36】: 尝试解压离线安装包离线安装包...
【2021年07月24日 14:50:37】: 安装包解压成功！继续！
【2021年07月24日 14:50:37】: 没有找到插件的web页面！
【2021年07月24日 14:50:37】: 你上传的文件可能不是koolshare软件中心离线安装包！
【2021年07月24日 14:50:37】: 退出本次离线安装！
【2021年07月24日 14:50:37】: 删除文件夹-1：/tmp/shadowsocks
【2021年07月24日 14:50:37】: 删除文件：/tmp/shadowsocks.tar.gz
【2021年07月24日 14:50:37】: ============================ end ================================

**Comment by alexallen1** [comment]
晕，这个项目2个月前的了。1个月前google全网搜梅林trojan xray怎么都没搜到这项目。觉得搜索关键词可以稍微改进下啊

**Comment by cary-sas** [comment]
> 晕，这个项目2个月前的了。1个月前google全网搜梅林trojan xray怎么都没搜到这项目。觉得搜索关键词可以稍微改进下啊
The purpose of this project is to develop for a couple of my friends and myself use. If others found any issues, can also report to me
