### ISSUE TITLE
无法科学上网

### ISSUE THREAD

**Issue by Aldolase** [cary-sas/v2ray_bin#10]
固件为tb梅林380
使用的是V2ray/xtls 节点，该节点在其它的机器上已经被证明可用
在节点管理页面下，ping 测试和web测试也都通过了
模式为大陆白名单模式
在DNS设定中，无论选择哪种国外DNS，均不能实现科学上网
在插件界面国外链接为x，浏览器中也无法科学上网

**Comment by bjtea** [comment]
> 升级到最新版，勾上“允许不安全”。

请问在哪勾选“允许不安全”

**Comment by bjtea** [comment]
我的是4.2.2，外网连不上。是vless，请问更新插件到最新的能否解决？

**Comment by cary-sas** [comment]
> > 升级到最新版，勾上“允许不安全”。
> 
> 请问在哪勾选“允许不安全”

需要删除原版本后安装我项目的安装包

**Comment by XiaoBaiLearning** [comment]
现在的最新版本是197，路由器里的科学上网这款插件不能用了，不管是自己搭建的节点还是买的节点，添加到这款插件里，国外连接永远都是X永远连不上。过一会儿IP就被封了。
