### ISSUE TITLE
请求更新能支持386使用

### ISSUE THREAD

**Issue by aprday** [cary-sas/v2ray_bin#13]
我的AC88U固件升级386了。降不下了。
fancyss他们的科学上网插件太落伍了
只支持SS、SSR、VMESS。
但我搞的都是VLESS科学上网协议。
专门为他搭建个VMESS在v2rayN可以上。在他上面不能行。
大佬能升级下程序吗？

**Comment by cary-sas** [comment]
用miniweb 降级回380
