### ISSUE TITLE
clash有些节点订阅显示是有的，但是在节点选择的时候没有

### ISSUE THREAD

**Issue by zlhdd108** [cary-sas/v2ray_bin#17]
clash有些节点订阅显示是有的，但是在节点选择的时候没有，如下图这个“香港节点”
![HE% 6DUCTRI0)D7YC6X{176](https://user-images.githubusercontent.com/16465666/150059372-542c3f6e-aaed-411b-af62-4e45709346cc.jpg)
但是在选择节点的时候没有
![image](https://user-images.githubusercontent.com/16465666/150059490-251a2af6-e5df-4289-8ae1-32f358d06a5a.png)
![image](https://user-images.githubusercontent.com/16465666/150059544-582f2bc1-f7d6-4cff-9252-77cad288858d.png)
在pc上用客户端是可以看到的
![image](https://user-images.githubusercontent.com/16465666/150059612-c656f520-3310-4d4a-ad32-a65c736e4505.png)

**Comment by zlhdd108** [comment]
发现了，好像不能点击“更新xray”和“更新v2ray”，这两个点击后，更新对应的二进制，同时订阅也有问题了；直接重装插件就是正常的……

**Comment by zlhdd108** [comment]
> 你卸载插件后，重新装最新版的，再订阅试试

好像是xray的问题，手动替换1.5.2后，更新订阅就会出现这个现象；但是直接删除所有节点，重新订阅是正常的，然后再更新订阅，依然会出现这个现象

**Comment by zlhdd108** [comment]
> 你卸载插件后，重新装最新版的，再订阅试试

卸载后重新安装是正常的；不过其实不需要重新安装，直接选择删除所有订阅节点，重新订阅，就是正常的；但是更新订阅，就会出现这个问题……

**Comment by cary-sas** [comment]
它可能是被重新排序了，你数一下节点的总数量对不对

**Comment by zlhdd108** [comment]
> 它可能是被重新排序了，你数一下节点的总数量对不对

总数时对的，一共52个，但是更新后有节点是重复的

### 左边是更新后的，右边是更新前正常的
![image](https://user-images.githubusercontent.com/16465666/150274365-447f0c3c-da9a-4f9a-89c6-c419b9e7d614.png)

### 这个是更新后重复的节点
![image](https://user-images.githubusercontent.com/16465666/150274479-3e25f935-b8a6-453c-a025-a626649c5eee.png)

**Comment by cary-sas** [comment]
![image](https://user-images.githubusercontent.com/61653855/150282049-5aa97aa4-2760-4d98-a63f-1ad574c30f0b.png)
修改ss_online_update.sh 试试

**Comment by zlhdd108** [comment]
> ![image](https://user-images.githubusercontent.com/61653855/150282049-5aa97aa4-2760-4d98-a63f-1ad574c30f0b.png) 修改ss_online_update.sh 试试

### 修改后还是不行
![image](https://user-images.githubusercontent.com/16465666/150283165-e2b52c64-9d7b-4e0d-b294-29f2e855cb17.png)

![image](https://user-images.githubusercontent.com/16465666/150283096-bc1a7741-d2f7-4ccd-865b-0176163eafb2.png)

### 发现在更新的时候这里不一样，HK节点提示没有更新；别的节点全部都提示有修改
![image](https://user-images.githubusercontent.com/16465666/150282895-27438f88-5b90-43be-8935-bb98c9c053a4.png)

**Comment by cary-sas** [comment]
你是删除所有节点后 操作的？

**Comment by zlhdd108** [comment]
> 你是删除所有节点后 操作的？

直接更新和删除后再添加更新都操作过，都是上面的结果

**Comment by cary-sas** [comment]
你有不同的名字节点， 但是IP或者域名信息是一样的吗 ？

**Comment by zlhdd108** [comment]
没有的，都是不同的

**Comment by cary-sas** [comment]
你试试这个，下载下来替换掉原来的，然后再试试。
https://gist.githubusercontent.com/cary-sas/dba5f2315886f8bfdcb0f11774f50030/raw/afa964f73990bd29046e384cd51001a820ad33a5/ss_online_update.sh

**Comment by zlhdd108** [comment]
> 你试试这个，下载下来替换掉原来的，然后再试试。 https://gist.githubusercontent.com/cary-sas/dba5f2315886f8bfdcb0f11774f50030/raw/afa964f73990bd29046e384cd51001a820ad33a5/ss_online_update.sh

### 这个是正常的
![image](https://user-images.githubusercontent.com/16465666/150451996-9d01b88a-9da1-47e8-9449-f0b7c799713a.png)
![image](https://user-images.githubusercontent.com/16465666/150452017-365985c5-7df3-4c8c-9ae6-fae3f86eaa0c.png)

**Comment by cary-sas** [comment]
其实就是你有不同节点名字，但是其实节点的地址是相同的，我后来改了逻辑  “如果在本地的订阅节点中已经有该节点（用group, remarks和server去判断），检测下配置是否更改，如果更改，则更新配置”

**Comment by zlhdd108** [comment]
> 其实就是你有不同节点名字，但是其实节点的地址是相同的，我后来改了逻辑 “如果在本地的订阅节点中已经有该节点（用group, remarks和server去判断），检测下配置是否更改，如果更改，则更新配置”

嗯，看到了；地址是相同的，但是端口和名字不同
