### ISSUE TITLE
vless + xtls 连不上

### ISSUE THREAD

**Issue by cloudzhong** [cary-sas/v2ray_bin#25]
请问我shadowrocket可以连上的，
但是这个连不上，应该如何设置xray？
加密方式
伪装类型
SNI
怎么设置?
我 vless , tcp / xtls / xtls-rprx-direct都设置了。

**Comment by cloudzhong** [comment]
可以了，参考了另外一个issue，换letsencrypt证书为zerossl就可以了。

**Comment by cary-sas** [comment]
是的。 
https://github.com/cary-sas/v2ray_bin/discussions/22
