### ISSUE TITLE
你好，请问r7000 的trojan go 不能用

### ISSUE THREAD

**Issue by kenny881** [cary-sas/v2ray_bin#26]
你好，请问r7000 的trojan go 怎么都不能用，其他的全部正常，请问问题出现在哪的？谢谢

**Comment by cary-sas** [comment]
你试试把留空的“[tls/xtls域名 (SNI)]” 里也填上 “[伪装域名 (host)]” 里的地址
<img width="200" alt="image" src="https://user-images.githubusercontent.com/61653855/166500046-fb0d40b5-4834-43eb-bb36-c703726a6793.png">

**Comment by kenny881** [comment]
试了，都不改变，切换成trojan就正常，目前猜测可能是tls跟ws之间的问题

**Comment by cary-sas** [comment]
你把trojan go 的二进制 退回到以前老版本的再试试

**Comment by cary-sas** [comment]
试试这个trojan go 的搭载脚本呢
`bash <(curl -s https://raw.githubusercontent.com/cary-sas/across/master/xray/xray_whatever_uuid.sh) $myuuid my.domain.com`

**Comment by cary-sas** [comment]
发现大概率是服务端证书的问题，一定要用 zerossl 的证书。如果要用CF优选IP 做反代，端口需要设成443
`~/.acme.sh/acme.sh --set-default-ca  --server zerossl`

**Comment by kenny881** [comment]
nice,it works！！脚本跟证书都对了，thanks! hey
