### ISSUE TITLE
大量请求DNS over TLS

### ISSUE THREAD

**Issue by rex5652** [cary-sas/v2ray_bin#33]
在V2Ray服务端看access日志，其中有大量 XXXXXX accepted tcp:1.0.0.1:853 [proxy] 和 XXXXXX accepted tcp:1.1.1.1:853 [proxy]
查了853端口是DNS over TLS，但在设置界面好像并没有启用DNS over TLS的设置。是否是程序里有什么东西会一直在检测吗？
谢谢

**Comment by cary-sas** [comment]
这些原因我也不懂，应该和本插件无关。
