### ISSUE TITLE
希望增加V2RAY和XRAY进程崩溃时的自启动脚本

### ISSUE THREAD

**Issue by mayaxcn** [cary-sas/v2ray_bin#39]
因部分路由器的内存容量有限，为256M内存。在某项极端大流量下载或观看4K视频时，容易导致V2RAY进程或XRAY因GOGC被强制终止，增加守护进程可完成自启动。

我已提交了部分自启动脚本，希望修改完善，Thx~

**Comment by cary-sas** [comment]
你的证书是 zerossl RSA 的吗

**Comment by mayaxcn** [comment]
？？我没使用tls，单纯只用KCP也发现家里几台设备同时看4K的时候，V2RAY会被强制GC掉，路由器的内存占用逐渐上升到240M零界点。

**Comment by cary-sas** [comment]
我可以试试加上，但是除了考虑v2ray，我这边还需要考虑 xray，trojan-go，v2ray-plugin 这些程序也要加上进程守护。

**Comment by mayaxcn** [comment]
的确是，v2ray和xray存在同样的问题，目前我是外接USB挂载成虚拟内存可以暂时缓一缓，但也不是长久之计。

PS:另外问问v2ray-plugin是用来做什么的？在top里没看到相关的进程存在

**Comment by cary-sas** [comment]
你可以自己google一下。
我就和你确认一下。你这样修改，测试下来是否可以解决你遇到的问题。

**Comment by mayaxcn** [comment]
只是能降低v2ray进程被kill的频率，正常浏览网页低负荷使用是没有问题的，但是如果我在看奈飞，女友在看油管，这时候内存就蹭蹭地增长，增长到零界点的时候进程被kill，然后就没有然后了。

所以还是希望增加一个进程守护的脚本监测到进程挂掉就自动重启

**Comment by cary-sas** [comment]
你要不先自己修改一下，跑一段时间试试看，如果好用的且能解决问题的话告诉我，我再修改。
_PS: 我看到你给的进程守护的程序是 “At every 15th minute.”检查一次，我的顾虑是，其实用户在使用高峰期遇到了进程崩溃，用户会停下来等待着让它定时自己检查并重启吗？ （要是我的话，还不是立马手动重启进程或者路由器了）_

**Comment by mayaxcn** [comment]
可能是笔误，我的原意是每15秒检测一次的

**Comment by cary-sas** [comment]
没事，你暂时先在你机器上试试呢。

**Comment by cary-sas** [comment]
> 因部分路由器的内存容量有限，为256M内存。在某项极端大流量下载或观看4K视频时，容易导致V2RAY进程或XRAY因GOGC被强制终止，增加守护进程可完成自启动。
> 
> 我已提交了部分自启动脚本，希望修改完善，Thx~

我测试下来，这个和你用的哪种协议有很大关系，kcp 本来就耗资源，我自己是vless xtls，家里即使几台设备都开4K 看视频，也不至于进程被杀掉，最多视频播放卡顿
