### ISSUE TITLE
ac88u,固件：386.3_2 无法安装

### ISSUE THREAD

**Issue by SimonWang110** [cary-sas/v2ray_bin#4]
【2021年09月30日 16:19:19】: ========================== step 1 ===============================
【2021年09月30日 16:19:19】: 开启插件离线安装！
【2021年09月30日 16:19:19】: 检测到你上传的离线安装包：shadows.tar.gz，安装包大小: 25.5M
【2021年09月30日 16:19:19】: 安装包md5sum校验值：1eff44cf3f0de4f8e5babfe2da592e02
【2021年09月30日 16:19:19】: 尝试解压离线安装包离线安装包...
【2021年09月30日 16:19:21】: 安装包解压成功！继续！
【2021年09月30日 16:19:21】: 没有找到插件的web页面！
【2021年09月30日 16:19:21】: 你上传的文件可能不是koolshare软件中心离线安装包！
【2021年09月30日 16:19:21】: 退出本次离线安装！
【2021年09月30日 16:19:21】: 删除文件夹-2：/tmp/shadowsocks
【2021年09月30日 16:19:21】: 删除文件：/tmp/shadows.tar.gz
【2021年09月30日 16:19:21】: ============================ end ================================

**Comment by cary-sas** [comment]
麻烦审题
